// <auto-generated />
using System;
using CorisSeguros.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorisSeguros.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924152027_TabelasDaDashboard")]
    partial class TabelasDaDashboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CorisSeguros.Api.Models.Apolice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CampanhaId")
                        .HasColumnType("int");

                    b.Property<int?>("CanalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("FimVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SeguradoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ValorPremioCentavos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("CanalId");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("SeguradoId");

                    b.HasIndex("Status");

                    b.ToTable("apolices", (string)null);
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApoliceId")
                        .HasColumnType("int");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("DentroSla")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Nps")
                        .HasColumnType("int");

                    b.Property<int>("TempoEsperaSeg")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ApoliceId");

                    b.HasIndex("Inicio");

                    b.ToTable("atendimentos", (string)null);
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Campanha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("date");

                    b.Property<int>("InvestimentoCentavos")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("OrcamentoCentavos")
                        .HasColumnType("int");

                    b.Property<string>("UtmSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("campanhas", (string)null);
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Canal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("canais", (string)null);
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Cotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApoliceId")
                        .HasColumnType("int");

                    b.Property<int?>("CampanhaId")
                        .HasColumnType("int");

                    b.Property<int>("CanalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Dias")
                        .HasColumnType("int");

                    b.Property<string>("EtapaAbandono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ValorCalculadoCentavos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApoliceId");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("CanalId");

                    b.HasIndex("CriadoEm", "Status");

                    b.ToTable("cotacoes", (string)null);
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.FunilEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CotacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoId", "Etapa");

                    b.ToTable("funil_eventos", (string)null);
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Segurado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("segurados", (string)null);
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Sinistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApoliceId")
                        .HasColumnType("int");

                    b.Property<string>("Cobertura")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateOnly>("DataAviso")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataOcorrencia")
                        .HasColumnType("date");

                    b.Property<string>("MotivoNegativa")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ValorPagoCentavos")
                        .HasColumnType("int");

                    b.Property<int>("ValorReclamadoCentavos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApoliceId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("Status", "DataAviso");

                    b.ToTable("sinistros", (string)null);
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Apolice", b =>
                {
                    b.HasOne("CorisSeguros.Api.Models.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("CampanhaId");

                    b.HasOne("CorisSeguros.Api.Models.Canal", "Canal")
                        .WithMany()
                        .HasForeignKey("CanalId");

                    b.HasOne("CorisSeguros.Api.Models.Segurado", "Segurado")
                        .WithMany("Apolices")
                        .HasForeignKey("SeguradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("Canal");

                    b.Navigation("Segurado");
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Atendimento", b =>
                {
                    b.HasOne("CorisSeguros.Api.Models.Apolice", "Apolice")
                        .WithMany()
                        .HasForeignKey("ApoliceId");

                    b.Navigation("Apolice");
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Cotacao", b =>
                {
                    b.HasOne("CorisSeguros.Api.Models.Apolice", "Apolice")
                        .WithMany()
                        .HasForeignKey("ApoliceId");

                    b.HasOne("CorisSeguros.Api.Models.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("CampanhaId");

                    b.HasOne("CorisSeguros.Api.Models.Canal", "Canal")
                        .WithMany()
                        .HasForeignKey("CanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apolice");

                    b.Navigation("Campanha");

                    b.Navigation("Canal");
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.FunilEvento", b =>
                {
                    b.HasOne("CorisSeguros.Api.Models.Cotacao", "Cotacao")
                        .WithMany("Eventos")
                        .HasForeignKey("CotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cotacao");
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Sinistro", b =>
                {
                    b.HasOne("CorisSeguros.Api.Models.Apolice", "Apolice")
                        .WithMany()
                        .HasForeignKey("ApoliceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apolice");
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Cotacao", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("CorisSeguros.Api.Models.Segurado", b =>
                {
                    b.Navigation("Apolices");
                });
#pragma warning restore 612, 618
        }
    }
}
